exports.token_names = ["Bitcoin", "Ethereum", "BNB", "XRP", "Dogecoin", "Cardano", "Polygon", "Polkadot", "Litecoin", "Shiba Inu", "Tron", "Solana", "Uniswap", "Avalanche", "Chainlink", 
"Monero", "Cosmos", "Ethereum Classic", "Stellar", "Bitcoin Cash", "ApeCoin", "Algorand", "Quant", "Filecoin", "VeChain", "NEAR Protocol", "Hedera", "Internet Computer", 
"MultiversX", "EOS", "Trust Wallet Token", "Flow", "Tezos", "Chiliz", "Aave", "Theta", "Axie Infinity", "Zcash", "Decentraland", "PancakeSwap", "Fantom", "Maker", "Aptos", "eCash", 
"Klaytn", "Dash", "Neo", "PAX Gold", "The Graph", "GMX", "Synthetix", "THORChain", "Osmosis", "Mina", "Stacks", "Nexo", "Basic Attention Token", "Curve DAO Token", "1inch Network", 
"Loopring", "Lido DAO", "ImmutableX", "NEM", "Decred", "Kava", "Enjin Coin", "Zilliqa", "Arweave", "Holo", "Convex Finance", "Compound", "Celo", "Balancer", "Ethereum Name Service", 
"Ravencoin", "SushiSwap", "Oasis Network", "yearn.finance", "Kusama", "Optimism", "Stepn", "Qtum", "Gnosis", "Theta Fuel", "IoTex", "Kadena", "Terra", "Mask Network", "Waves",
"Ankr", "JUST", "Moonbeam", "Harmony", "Gala", "Livepeer", "JasmyCoin", "Reserve Rights", "Hive", "ICON", "0x", "OMG Network", "Astar", "Ontology", "BinaryX", "IOST", "WOO Network", 
"SafePal", "Amp", "Flux", "Audius", "Siacoin", "Horizen", "WAX", "Storj", "Render Token", "DigiByte", "SXP", "Secret", "Injective", "UMA", "PlayDAPP", "ConstitutionDAO", 
"Ocean Protocol", "dYdX", "Smooth Love Position", "Lisk", "Nano", "Kyber Network Crystal v2", "Pundi X", "SKALE", "Voyager Token", "Request", "Aragon", "Frax Share", "Illuvium", 
"iExec RLC", "Vulcan Forged PYR", "Celer Network", "Ontology Gas", "Ren", "Biconomy", "Nervos Network", "Numeraire", "Chromia", "MAGIC", "Hooked Protocol", "DeXe", "Syscoin", 
"API3", "Hashflow", "Mdex", "COTI", "Cartesi", "MOBOX", "Ardor", "Biswap", "Steem", "Fetch.ai", "FUNToken", "Acala Token", "Alpha Venture DAO", "Powerledger", "MobileCoin", 
"aelf", "Dent", "Stratis", "Band Protocol", "Shentu", "Hifi finance", "Spell Token", "WazirX", "Polymesh", "Bancor", "Reef", "Augur", "Phala Network", "JOE", "Orchid", "NKN",
"Conflux", "Radicle", "Venus", "Stargate Finance", "Ampleforth Governance Token", "DFO.Money", "LeverFi", "Alien Worlds", "STP", "Origin Protocol", "Coin98", "SUN", "StormX", 
"Galxe", "Metal DAO", "Utrust", "DODO", "RSK Infrastructure Framework", "Moonriver", "VeThor Token", "Beta Finance", "Alchemy Pay", "Aavegotchi", "Verge", "Badger DAO", 
"Enzyme", "Marlin", "Propetual Protocol", "Cocos-BCX", "SuperVerse", "S.S.Lazio Fan Token", "BarnBridge", "Polkstarter", "MyNeighborAlice", "Automata Network", "Dusk Network", 
"Alpaca Finance", "Toko Token", "ARPA", "Neblio", "Cortex", "BakeryToken", "TrueFi", "IDEX", "Travala.com", "Wanchain", "Bounce Governance Token", "Keep3rV1", "LTO Network", 
"Virtua", "Ethernity", "Orion Protocol", "Tellor", "Raydium", "Litentry", "League of Kingdoms Arena", "Beefy Finance", "DIA", "Alpine F1 Team Fan Token", "Komodo", "BitShares", 
"Alchemix", "Linear Finance", "VIDT DAO", "CLV", "QuickSwap", "Flamingo", "Mines of Dalarnia", "Santos FC Fan Token", "NULS", "Yield Guild Games", "FC Porto Fan Token", 
"MIOTA", "Bluzelle", "Helium", "Bella Protocol", "Axie Infinity", "Gitcoin"];

exports.token_tickers = ["BTC", "ETH", "BNB", "XRP", "DOGE", "ADA", "MATIC", "DOT", "LTC", "SHIB", "TRX", "SOL", "UNI", "AVAX", "LINK", "XMR", "ATOM", "ETC", "XLM", "BCH", "APE", 
"ALGO", "QNT", "FIL", "VET", "NEAR", "HBAR", "ICP", "EGLD", "EOS", "TWT", "FLOW", "XTZ", "CHZ", "AAVE", "THETA", "SAND", "ZEC", "MANA", "CAKE", "FTM", "MKR", "APT", "XEC", "KLAY", 
"DASH", "NEO", "PAXG", "GRT", "GMX", "SNX", "RUNE", "OSMO", "MINA", "STX", "NEXO", "BAT", "CRV", "1INCH", "LRC", "LDO", "IMX", "XEM", "DCR", "KAVA", "ENJ", "ZIL", "AR", "HOT", 
"CVX", "COMP", "CELO", "BAL", "ENS", "RVN", "SUSHI", "ROSE", "YFI", "KSM", "OP", "GMT", "QTUM", "GNO", "TFUEL", "IOTX", "KDA", "LUNA", "MASK", "WAVES", "ANKR", "JST", "GLMR", 
"ONE", "GALA", "LPT", "JASMY", "RSR", "HIVE", "ICX", "ZRX", "OMG", "ASTR", "ONT", "BNX", "IOST", "WOO", "SFP", "AMP", "FLUX", "AUDIO", "SC", "ZEN", "WAXP", "STORJ", "RNDR", "DGB", 
"SXP", "SCRT", "INJ", "UMA", "PLA", "PEOPLE", "OCEAN", "DYDX", "SLP", "LSK", "XNO", "KNC", "PUNDIX", "SKL", "VGX", "REQ", "ANT", "FXS", "ILV", "RLC", "PYR", "CELR", "ONG", "REN", 
"BICO", "CKB", "NMR", "CHR", "MAGIC", "HOOK", "DEXE", "SYS", "API3", "HFT", "MDX", "COTI", "CTSI", "MBOX", "ARDR", "BSW", "STEEM", "FET", "FUN", "ACA", "ALPHA", "POWR", "MOB", 
"ELF", "DENT", "STRAX", "BAND", "CTK", "MFT", "SPELL", "WRX", "POLYX", "BNT", "REEF", "REP", "PHA", "JOE", "OXT", "NKN", "CFX", "RAD", "XVS", "STG", "FORTH", "YFII", "LEVER", 
"TLM", "STPT", "OGN", "C98", "SUN", "STMX", "GAL", "MTL", "UTK", "DODO", "RIF", "MOVR", "VTHO", "BETA", "ACH", "GHST", "XVG", "BADGER", "MLN", "POND", "PERP", "COCOS", 
"SUPER", "LAZIO", "BOND", "POLS", "ALICE", "ATA", "DUSK", "ALPACA", "TKO", "ARPA", "NEBL", "CTXC", "BAKE", "TRU", "IDEX", "AVA", "WAN", "AUCTION", "KP3R", "LTO", "TVK", "ERN", 
"ORN", "TRB", "RAY", "LIT", "LOKA", "BIFI", "DIA", "ALPINE", "TOMO", "BTS", "ALCX", "LINA", "VIDT", "CLV", "QUICK", "FLM", "DAR", "SANTOS", "NULS", "YGG", "PORTO", 
"IOTA", "BLZ", "HNT", "BEL", "AXS", "GTC"];